/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_user_zziccook_TabLayoutActivity */

#ifndef _Included_com_example_user_zziccook_TabLayoutActivity
#define _Included_com_example_user_zziccook_TabLayoutActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_user_zziccook_TabLayoutActivity_REQUEST_CAMERA
#define com_example_user_zziccook_TabLayoutActivity_REQUEST_CAMERA 0L
#ifdef __cplusplus
}
#endif
#endif
