/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_user_zziccook_VolumeMeasureActivity */

#ifndef _Included_com_example_user_zziccook_VolumeMeasureActivity
#define _Included_com_example_user_zziccook_VolumeMeasureActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
